create table if not exists categories (
    id integer generated by default as identity,
    description varchar(100) not null unique,
    primary key (id)
);

insert into categories (description) values
('Comentário'),
('Crítica'),
('Elogio'),
('Sugestão');